version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - run: npm install
      - run:
          name: "build react app"
          command: |
            npm run build

      - add_ssh_keys:
          fingerprints:
            - "57:6e:37:24:ca:39:51:a0:ac:e5:3a:da:8d:d4:cd:01"
      - run:
          name: Deploy Over SSH
          command: |
            scp -r -o StrictHostKeyChecking=no ~/project/build/* $SSH_USER@$SSH_TARGET

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
